---
fixtures:
  repositories:
    cron_core: 'https://github.com/puppetlabs/puppetlabs-cron_core'
    provision: 'https://github.com/puppetlabs/provision'
    bootstrap: 'https://github.com/puppetlabs/puppetlabs-bootstrap'
    puppet_conf: 'https://github.com/puppetlabs/puppetlabs-puppet_conf'
    deploy_pe: 'https://github.com/jarretlavallee/puppet-deploy_pe'
    ruby_task_helper: 'https://git@github.com/puppetlabs/puppetlabs-ruby_task_helper'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib' 
    facts: 'https://github.com/puppetlabs/puppetlabs-facts'
    puppet_enterprise:
      repo: git@github.com:puppetlabs/puppetlabs-puppet_enterprise.git

