---
mock_with: ':rspec'

appveyor.yml:
  delete: true
.project:
  delete: true
.gitlab-ci.yml:
  delete: true 

spec/default_facts.yml:
  extra_facts:
    pe_server_version: 2018.1.0
    memory:
      "system":
        "total": "16.00 GiB"
        "total_bytes": 17179869184
    processors:
      "count": 8

.travis.yml:
  includes:
    - env: PUPPET_GEM_VERSION="= 4.6.1" CHECK=parallel_spec
      rvm: 2.1.9
